export const THEME_STORAGE_KEY = "theme";

const GPA_STORAGE_NAMESPACE = "aoun:gpa";
const GPA_STORAGE_VERSION = "v1";

export const GPA_SUPPORTS_42_SCALE_STORAGE_KEY =
  `${GPA_STORAGE_NAMESPACE}:supports-42-scale:${GPA_STORAGE_VERSION}`;
export const GPA_GRADE_TYPE_STORAGE_KEY =
  `${GPA_STORAGE_NAMESPACE}:grade-type:${GPA_STORAGE_VERSION}`;
export const GPA_CALCULATOR_HISTORY_STORAGE_KEY = "gpaCalculatorHistory:v1";

const STUDENT_STORAGE_NAMESPACE = "aoun:student";
const STUDENT_STORAGE_VERSION = "v1";

export const COURSE_STATUS_STORAGE_KEY =
  `${STUDENT_STORAGE_NAMESPACE}:course-status:${STUDENT_STORAGE_VERSION}`;
export const LAST_MAJOR_STORAGE_KEY =
  `${STUDENT_STORAGE_NAMESPACE}:last-major:${STUDENT_STORAGE_VERSION}`;
export const CUSTOM_COURSES_STORAGE_KEY =
  `${STUDENT_STORAGE_NAMESPACE}:custom-courses:${STUDENT_STORAGE_VERSION}`;
export const COURSE_STATUS_FILTER_STORAGE_KEY =
  `${STUDENT_STORAGE_NAMESPACE}:course-filter:${STUDENT_STORAGE_VERSION}`;
export const RECENT_GLOBAL_COURSE_SEARCHES_STORAGE_KEY =
  `${STUDENT_STORAGE_NAMESPACE}:recent-global-course-searches:${STUDENT_STORAGE_VERSION}`;

export const ACADEMIC_CALENDAR_STORAGE_KEY = "aoun:academic-calendar:v1";
export const FOCUS_SOUND_PREFERENCES_STORAGE_KEY = "aoun:focus-sounds:v1";

export const USER_DATA_LOCAL_STORAGE_KEYS = [
  THEME_STORAGE_KEY,
  GPA_SUPPORTS_42_SCALE_STORAGE_KEY,
  GPA_GRADE_TYPE_STORAGE_KEY,
  GPA_CALCULATOR_HISTORY_STORAGE_KEY,
  COURSE_STATUS_STORAGE_KEY,
  LAST_MAJOR_STORAGE_KEY,
  CUSTOM_COURSES_STORAGE_KEY,
  COURSE_STATUS_FILTER_STORAGE_KEY,
  RECENT_GLOBAL_COURSE_SEARCHES_STORAGE_KEY,
  ACADEMIC_CALENDAR_STORAGE_KEY,
  FOCUS_SOUND_PREFERENCES_STORAGE_KEY,
] as const;

export type UserDataLocalStorageKey =
  (typeof USER_DATA_LOCAL_STORAGE_KEYS)[number];
